export const API_ENDPOINTS = {
  REGISTER: 'auth/register',
  LOGIN: 'auth/login',
  REFRESH_TOKEN: 'auth/refresh-token',
  GOOGLE_AUTH: 'auth/google',
  FETCH_ORDERS: 'orders/by-user',
  BIOMETRIC_REGISTER_START: 'auth/biometric/register/start',
  BIOMETRIC_REGISTER_VERIFY: 'auth/biometric/register/verify',
  BIOMETRIC_LOGIN_START: 'auth/biometric/login/start',
  BIOMETRIC_LOGIN_VERIFY: 'auth/biometric/login/verify',
  BIOMETRIC_DISABLE: 'auth/biometric/disable',
  SSL_PINNING_ECHO: 'ssl-pinning/echo-request',
  DRIVE_ROOT: 'drive/root',
  DRIVE_FOLDERS: 'drive/folders',
  DRIVE_FILES: 'drive/files',
  DRIVE_ITEMS: 'drive/items',
  DRIVE_UPLOADS_REQUEST: 'drive/uploads/request',
  DRIVE_UPLOADS_CONFIRM: 'drive/uploads/confirm',
};
