export const ROUTES = {
  APP_NAVIGATOR: 'AppNavigator',
  AUTH_NAVIGATOR: 'AuthNavigator',
  SPLASH: 'SplashScreen',
  LOGIN: 'LoginScreen',
  REGISTER: 'RegisterScreen',
  HOME: 'HomeScreen',
  APP_RELOAD: 'AppReloadScreen',
  CARDS_ROTATE: 'CardsRotateScreen',
  SCROLL_ANIMATION: 'ScrollAnimationScreen',
  File_SAVE_AND_DOWNLOAD: 'FileSaveAndDownloadScreen',
  WELCOME_ALERT: 'WelcomeAlertScreen',
  BIOMETRICS: 'BiometricScreen',
  TEXT_EDITOR: 'TextEditorScreen',
  CHECKBOX_ANIMATION: 'CheckboxAnimationScreen',
} as const;
