export const ROUTES = {
  APP_NAVIGATOR: 'AppNavigator',
  AUTH_NAVIGATOR: 'AuthNavigator',
  SPLASH: 'SplashScreen',
  LOGIN: 'LoginScreen',
  REGISTER: 'RegisterScreen',
  HOME: 'HomeScreen',
  CARDS_ROTATE: 'CardsRotateScreen',
  SCROLL_ANIMATION: 'ScrollAnimationScreen',
  FILE_SAVE_AND_DOWNLOAD: 'FileSaveAndDownloadScreen',
  WELCOME_ALERT: 'WelcomeAlertScreen',
  BIOMETRICS: 'BiometricScreen',
  TEXT_EDITOR: 'TextEditorScreen',
  CHECKBOX_ANIMATION: 'CheckboxAnimationScreen',
  SELECT_DROPDOWNS: 'SelectDropdowns',
  SSL_PINNING: 'SSLPinningScreen',
  DEVICE_INFO: 'DeviceInfoScreen',
} as const;
